// ─── ElectroDSL SPICE Netlist Exporter ───────────────────────────────────────
window.ElectroSPICE = (function () {

  function buildNodeMap(ast) {
    // Assign net numbers to connected components
    const nets = {};
    let netNum = 1;

    // Grounds are net 0
    Object.values(ast.components).forEach(c => {
      if (c.type === 'Ground') nets[c.id] = 0;
      else if (c.type === 'VCC') nets[c.id] = 'VCC';
    });

    // Walk wires to propagate nets
    function getNet(id) {
      if (nets[id] !== undefined) return nets[id];
      nets[id] = netNum++;
      return nets[id];
    }

    ast.wires.forEach(w => {
      const nf = getNet(w.from);
      const nt = getNet(w.to);
      // merge: use lower net for both
      if (typeof nf === 'number' && typeof nt === 'number' && nf !== nt && nf !== 0 && nt !== 0) {
        const keep = Math.min(nf, nt), replace = Math.max(nf, nt);
        Object.keys(nets).forEach(k => { if (nets[k] === replace) nets[k] = keep; });
      } else if (nf === 0 && typeof nt === 'number') {
        Object.keys(nets).forEach(k => { if (nets[k] === nt) nets[k] = 0; });
      } else if (nt === 0 && typeof nf === 'number') {
        Object.keys(nets).forEach(k => { if (nets[k] === nf) nets[k] = 0; });
      }
    });

    // Assign remaining
    Object.values(ast.components).forEach(c => {
      if (nets[c.id] === undefined) nets[c.id] = netNum++;
    });

    return nets;
  }

  function formatValue(params) {
    if (!params) return '1k';
    return params.replace(/\s+/g, '').replace(/Ω/g, '').replace(/ohm/gi,'');
  }

  function toSPICE(ast) {
    const lines = [];
    const title = ast.title || 'ElectroDSL Schematic';
    lines.push(`* ${title}`);
    lines.push(`* Generated by ElectroDSL`);
    lines.push(`* ${new Date().toISOString()}`);
    lines.push('');

    const nets = buildNodeMap(ast);
    const comps = Object.values(ast.components);

    comps.forEach(c => {
      const n1 = nets[c.id] ?? 1;
      const val = formatValue(c.params);

      switch (c.type) {
        case 'VSource':
          lines.push(`${c.id} ${n1} 0 ${c.params.includes('AC') ? 'AC' : 'DC'} ${val}`);
          break;
        case 'ISource':
          lines.push(`${c.id} ${n1} 0 DC ${val}`);
          break;
        case 'Resistor':
          lines.push(`${c.id} ${n1} 0 ${val}`);
          break;
        case 'Capacitor':
          lines.push(`${c.id} ${n1} 0 ${val}`);
          break;
        case 'Inductor':
          lines.push(`${c.id} ${n1} 0 ${val}`);
          break;
        case 'Diode':
          lines.push(`${c.id} ${n1} 0 D1N4148`);
          lines.push(`.model D1N4148 D(Is=2.52n Rs=0.568 N=1.752)`);
          break;
        case 'LED':
          lines.push(`${c.id} ${n1} 0 DLED`);
          lines.push(`.model DLED D(Is=10p N=2.0 Vfwd=2.0)`);
          break;
        case 'Zener':
          lines.push(`${c.id} 0 ${n1} DZ ${val || '5.1V'}`);
          lines.push(`.model DZ D(BV=${val || '5.1'} IBV=5m)`);
          break;
        case 'NPN':
          lines.push(`${c.id} NC_C NC_B NC_E ${c.params || '2N2222'}`);
          lines.push(`.model 2N2222 NPN(Is=14.34f Xti=3 Eg=1.11 Vaf=74.03 Bf=255.9)`);
          break;
        case 'PNP':
          lines.push(`${c.id} NC_C NC_B NC_E ${c.params || '2N3906'}`);
          lines.push(`.model 2N3906 PNP(Is=1.41f Xti=3 Eg=1.11 Vaf=18.7 Bf=180.7)`);
          break;
        case 'NMOS':
          lines.push(`${c.id} NC_D NC_G NC_S ${c.params || 'NMOD'}`);
          lines.push(`.model NMOD NMOS(VTO=2 KP=2u)`);
          break;
        case 'PMOS':
          lines.push(`${c.id} NC_D NC_G NC_S ${c.params || 'PMOD'}`);
          lines.push(`.model PMOD PMOS(VTO=-2 KP=2u)`);
          break;
        case 'OpAmp':
          lines.push(`* OpAmp ${c.id} (${c.params || 'LM741'}) - OUT IN+ IN-`);
          lines.push(`${c.id} NC_OUT NC_P NC_N OPAMP`);
          lines.push(`.subckt OPAMP IN+ IN- OUT`);
          lines.push(`E1 OUT 0 IN+ IN- 1Meg`);
          lines.push(`.ends OPAMP`);
          break;
        case 'Ground': case 'Node': case 'VCC':
          break; // structural only
        default:
          lines.push(`* ${c.id}: ${c.type} (${c.params})`);
      }
    });

    lines.push('');
    lines.push('.op');
    lines.push('.tran 1us 1ms');
    lines.push('.end');

    return lines.join('\n');
  }

  // KiCad netlist format
  function toKiCad(ast) {
    const lines = [];
    lines.push('(net_list');
    lines.push(`  (title "${ast.title || 'ElectroDSL'}")`);
    lines.push('  (components');
    Object.values(ast.components).forEach(c => {
      if (['Ground','Node','VCC'].includes(c.type)) return;
      lines.push(`    (comp (ref ${c.id})`);
      lines.push(`      (value "${c.params || c.type}")`);
      lines.push(`      (description "${c.type}")`);
      lines.push(`    )`);
    });
    lines.push('  )');
    lines.push(')');
    return lines.join('\n');
  }

  return { toSPICE, toKiCad };
})();
